on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Conan
        run: pip install "conan" pytest && conan --version
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.26.x'
      - name: Conan Detect Profile
        run: conan profile detect --force
      - name: Conan Install Deps
        run: conan install . --output-folder=build --build=missing
      - name: Run CMake
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/runner/work/ecc-tbp/ecc-tbp/build/build/Release/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
      - name: Run Tests
        run: ls build