on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Conan
        run: pip install "conan" pytest && conan --version
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.26.x'
      - name: Conan Use
        run: conan install . --output-folder=build --build=missing
      - name: Run Tests
        run: cmake -S . -B build -G "Unix Makefiles" && ctest