on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Conan
        run: pip install "conan" pytest && conan --version
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.0
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.26.x'
      - name: Conan Detect Profile
        run: conan profile detect --force
      - name: Conan Install Deps
        run: conan install . --output-folder=build --build=missing
      - name: Run CMake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake -G Ninja -S . -B ./cmake-build-debug
      - name: Run Tests
        run: ./cmake-build-debug/tests/google_tests_run